export const ActionTypes = {
  NODES_ACTIONS: {
    GET_NODES: "GET_NODES",
    SET_NODES: "SET_NODES",
    ADD_NODE: "ADD_NODE"
  },
  REQUEST_ACTIONS: {
    REQUEST_SUCCESS: "REQUEST_SUCCESS",
    REQUEST_FAILURE: "REQUEST_FAILURE",
    RESET_REQUEST: "RESET_REQUEST",
    REQUEST_INPROGRESS: "INPROGRESS_REQUEST"
  },
};

export default ActionTypes;
