export const ActionTypes = {
  NODES_ACTIONS: {
    GET_NODES: "GET_NODES",
    SET_NODES: "SET_NODES",
    ADD_NODE: "ADD_NODE",
    ADD_NODE_SUCCESS:"ADD_NODE_SUCCESS",
    ADD_NODE_FAILURE:"ADD_NODE_FAILURE"
  },
  REQUEST_ACTIONS: {
    REQUEST_SUCCESS: "REQUEST_SUCCESS",
    REQUEST_FAILURE: "REQUEST_FAILURE",
    RESET_REQUEST: "RESET_REQUEST",
    REQUEST_INPROGRESS: "INPROGRESS_REQUEST"
  },
  NOTIFICATION_ACTIONS: {
    ADD_NOTIFICATION:"ADD_NOTIFICATION"
  }
};

export default ActionTypes;
